# Generated by Django 6.0.4 on 2026-04-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appartement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Appartement (code)')),
                ('appellation', models.CharField(max_length=100, verbose_name='Appellation')),
                ('loyer_mensuel_attendu', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Loyer mensuel attendu')),
                ('devise', models.CharField(default='FCFA', max_length=20, verbose_name='Devise / unité')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
            ],
            options={
                'verbose_name': 'Appartement',
                'verbose_name_plural': 'Appartements',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='DepenseFixeMensuelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Désignation')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Montant')),
                ('devise', models.CharField(default='FCFA', max_length=20, verbose_name='Devise')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
            ],
            options={
                'verbose_name': 'Dépense fixe mensuelle',
                'verbose_name_plural': 'Dépenses fixes mensuelles',
                'ordering': ['nom'],
            },
        ),
    ]
